apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
  labels:
    app: ace-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace-app
  template:
    metadata:
      labels:
        app: ace-app
    spec:
      containers:
        - name: ace-container
          image: my-ace-app:latest
          ports:
            - containerPort: 7600